services:
  - type: web
    name: krishiseva
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_VERSION
        value: 22.22.0
